In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,precision_score
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score,precision_score,recall_score,f1_score


In [3]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [5]:
sns.set_theme()
iris = sns.load_dataset("iris")
print(iris.head())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


In [27]:
# LOGISTIC REGRESSION .....

# encoding...

x = iris.drop(columns = "species",axis = 1)
y = iris["species"]

# split the data...

x_train,x_test,y_train,y_test = train_test_split(
    x,y,test_size = 0.2,random_state = 1000
)

# scaling...
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

# train the data...

model = LogisticRegression(max_iter = 200)
model.fit(x_train,y_train)

# predict...

y_pred = model.predict(x_test)

# evaluation...
print(y_pred[:6])
cm = confusion_matrix(y_test,y_pred)
print(cm)
print("accuruacy score is : ",accuracy_score(y_test,y_pred))
print("precision_score is : ", precision_score(y_test, y_pred, average='weighted'))
print("recall score is : ",recall_score(y_test,y_pred,average = 'weighted'))
print("f1 score is : ",f1_score(y_test,y_pred,average = 'weighted'))

['versicolor' 'setosa' 'virginica' 'virginica' 'setosa' 'setosa']
[[ 9  0  0]
 [ 0 11  1]
 [ 0  1  8]]
accuruacy score is :  0.9333333333333333
precision_score is :  0.9333333333333333
recall score is :  0.9333333333333333
f1 score is :  0.9333333333333333


In [28]:
# NAIVE BAYES .....

from sklearn.naive_bayes import GaussianNB

g_model = GaussianNB()
g_model.fit(x_train,y_train)
y2_pred = g_model.predict(x_test)

print("accuracy_score is : ",accuracy_score(y_test,y2_pred))
print("recall score is : ",recall_score(y_test,y2_pred,average = 'weighted'))
print("precision score is : ",precision_score(y_test,y2_pred,average = 'weighted'))

accuracy_score is :  0.9333333333333333
recall score is :  0.9333333333333333
precision score is :  0.9333333333333333


In [30]:
# KNN ....
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors = 7)
knn_model.fit(x_train,y_train)
y3_pred = knn_model.predict(x_test)

print("accuracy score is : ",accuracy_score(y_test,y3_pred))
print("recall score is : ",recall_score(y_test,y3_pred,average = 'weighted'))
print("precision score is : ",precision_score(y_test,y3_pred,average='weighted'))

accuracy score is :  0.9666666666666667
recall score is :  0.9666666666666667
precision score is :  0.9692307692307692
