In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)
print()
arr2D = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr2D)
print()
print(arr + arr2D)

[1 2 3 4 5]

[[1 2 3 4 5]
 [1 2 3 4 5]]

[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]
