In [1]:
import numpy as np

In [3]:
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))
sum_of_columns = np.sum(arr2D,axis = 0)
print(sum_of_columns)
sum_of_rows = np.sum(arr2D,axis = 1)
print(sum_of_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]


In [4]:
#slicing in 2D  array
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)
print(arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2]
 [5]]


In [11]:
#3D array
arr3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3D,arr3D.shape)

#indexing
print(arr3D[1,1,0])

#slicing
print(arr3D[:,0,:])
print(arr3D[:,:,1])
print(arr3D[1,:,:])
print(arr3D[0:2,1,1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] (2, 2, 3)
10
[[1 2 3]
 [7 8 9]]
[[ 2  5]
 [ 8 11]]
[[ 7  8  9]
 [10 11 12]]
[ 5 11]


In [15]:
#manipulation
arr3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3D)
print()

arr3D[:,0,:]=99
print(arr3D)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

[[[99 99 99]
  [ 4  5  6]]

 [[99 99 99]
  [10 11 12]]]
