In [3]:
import numpy as np

In [4]:
#create from lists
arr = np.array([1,2,3,4,5])
print(arr,type(arr),arr.dtype,arr.shape)

arr2 = np.array([1,2,3,4,5,"prime"])
print(arr2,type(arr2), arr2.shape,arr2.dtype)

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D,arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> (6,) <U21
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [10]:
arr1 =  np.zeros((2,3), dtype="int64")#prefill
print(arr1,arr1.shape)

arr2 = np.ones((3,4), dtype="int64")
print(arr2,arr2.shape)

arr3 = np.full((3,4),100)
print(arr3,arr3.shape)

arr4 = np.eye(3)
print(arr4,arr4.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] (3, 4)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)


In [11]:
arr5 = np.arange(0,11,2)
print(arr5,arr5.shape)

[ 0  2  4  6  8 10] (6,)


In [12]:
arr6 = np.linspace(1,100,3)
print(arr6,arr6.shape)

[  1.   50.5 100. ] (3,)


In [13]:
print(arr4.size)

9


In [14]:
print(arr4.ndim)

2


In [15]:
float_arr = arr1.astype(np.float64)
print(float_arr,float_arr.dtype)

[[0. 0. 0.]
 [0. 0. 0.]] float64
