In [2]:
#reshaping
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)
reshaped = arr.reshape((3,2))
print(reshaped,reshaped.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [9]:
flat = arr.flatten()
print(flat,flat.shape)

[1 2 3 4 5 6] (6,)


In [ ]:
#indexing

In [10]:
print(arr[1])

[4 5 6]


In [11]:
 print(flat[1])

2


In [13]:
print(arr[1][1])

5


In [14]:
#fancy indexing
arr = np.array([1,2,3,4,5,6])
idx = [0,2,3]
print(arr[idx])

[1 3 4]


In [15]:
#boolean indexing
arr = np.array([1,2,3,4,5,7])
print(arr[arr>2])
print(arr[arr%2==0])
print(arr[arr%2!=0])

[3 4 5 7]
[2 4]
[1 3 5 7]


In [16]:
#slicing
arr = np.array([1,2,3,4,5,6])
print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[::2])

[2 3 4]
[2 3 4 5 6]
[1 2 3 4]
[1 3 5]


In [18]:
#copy vs view
nums = [1,2,3,4,5]
sub_list = nums[1:3]
sub_list[0] = 100
print(nums)
print(sub_list)

arr = np.array(nums)
sub_arr = arr[1:3]
sub_arr2 = arr[1:3].copy()
sub_arr[0] = 100
sub_arr2[1] = 200
print(arr)
print(sub_arr)
print(sub_arr2)

[1, 2, 3, 4, 5]
[100, 3]
[  1 100   3   4   5]
[100   3]
[  2 200]
