In [1]:
import numpy as np


In [3]:
arr = np.array([1,2,3,4,5])
arr2 = np.array([5,6,7,8,9])
print(arr)
print(arr ** 2)
print(arr + 10)
print(arr2)
print(arr + arr2)

[1 2 3 4 5]
[ 1  4  9 16 25]
[11 12 13 14 15]
[5 6 7 8 9]
[ 6  8 10 12 14]
